# Generated by Django 4.1.3 on 2023-05-09 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('name',), 'verbose_name_plural': 'Channels'},
        ),
        migrations.RemoveField(
            model_name='channel_link',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='channel_link',
            name='user_id',
        ),
        migrations.AddField(
            model_name='channel_link',
            name='channel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='channel.channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel_link',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
