# Generated by Django 4.1.3 on 2023-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Group',
            new_name='group',
        ),
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
