# Generated by Django 4.1.3 on 2023-06-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_rename_timestamp_message_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
