# Generated by Django 4.1.3 on 2023-05-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='isAccepted',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('R', 'rejected')], default=False, max_length=100),
        ),
    ]
