# Generated by Django 4.1.3 on 2023-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_friendrequest_fromuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
