# Generated by Django 4.1.3 on 2023-05-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('request', '0005_alter_friendrequest_fromuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
